title: Robotic Tutorials
author: Niko Roßkopf
email: roboter.tutorials.german@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Arduino und Elektronik Tutorials auf deutsch!

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d. %B %Y"

  # generate social links in footer
  social_links:
    github:  nikoro1904
#    rss: rss
    # youtube: Robotic Tutorials
    # youtube_channel: UCT7OJquYzFHHpyjkZL8APFw
    # youtube_channel_name: Robotic Tutorials

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
